let tableInfo = [
  {
    id: 1,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 85,
    sort: "",
    price: 40000,
  },
  {
    id: 2,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 3,
    size: 70,
    sort: "",
    price: 30000,
  },
  {
    id: 3,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 2,
    size: 56,
    sort: "",
    price: 20000,
  },
  {
    id: 4,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 100,
    sort: "",
    price: 60000,
  },
  {
    id: 4,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 100,
    sort: "",
    price: 60000,
  },
  {
    id: 4,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 100,
    sort: "",
    price: 60000,
  },
  {
    id: 4,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 100,
    sort: "",
    price: 60000,
  },
  {
    id: 4,
    country: "Uzbekistan",
    region: "Osiyo",
    city: "Tashkent",
    zipCode: "998",
    rooms: 4,
    size: 100,
    sort: "",
    price: 60000,
  },
];
export default tableInfo;
