export let studentInfo = [
  {
    id: 1,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 2,
    name: "Bosimov Jaloliddin",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 3,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 4,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 5,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 6,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 6,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 8,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 9,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 10,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 11,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 12,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
  {
    id: 13,
    name: "Jaloliddin Bosimov",
    age: "24",
    address: "Sirdaryo Uzbekiston",
    status: "student",
    nickname: "Umar",
    univ: "TATU",
    job: "developer",
  },
];
